In [32]:
import numpy as np 
import pandas as pd
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.model_selection import train_test_split # Import train_test_split function
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation


In [33]:
import pandas as pd
dataset = pd.read_csv("student_data.csv")
#df

In [34]:
# Solit features and respose 
X = np.array(dataset.iloc[:,0:25])
Y = np.array(dataset.iloc[:,25:26])

In [35]:
print(X)

[[1 1 0 ... 1 0 0]
 [1 0 1 ... 1 1 0]
 [1 0 1 ... 0 1 0]
 ...
 [1 0 1 ... 1 1 1]
 [1 1 0 ... 0 1 0]
 [1 1 0 ... 1 0 1]]


In [36]:
print(Y.shape)

(398, 1)


In [37]:
from sklearn.model_selection import KFold
n_split = 4 
for train_index,test_index in KFold(n_split).split(X):
    x_train,x_test = X[train_index],X[test_index]
    y_train,y_test = Y[train_index],Y[test_index]
   

In [43]:
# Create Decision Tree classifer object
clf = DecisionTreeClassifier()

# Train Decision Tree Classifer
clf = clf.fit(x_train,y_train)

#Predict the response for test dataset
y_pred = clf.predict(x_test)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))


Accuracy: 1.0


In [44]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(clf, x_train, y_train, cv=5)
scores_mean = scores.mean();
scores_mean

0.8393164767991108

In [40]:
res = y_pred
for i in range(len(y_pred)):
    if(y_pred[i] > 0.5):
        res[i] = 1
    else:
        res[i] = 0 

In [41]:
TP = 0 
FP = 0
FN = 0 
TN = 0
for j in range(len(y_test)):
    if(y_test[j] == 1 and res[j] == 1):
        TP = TP + 1
    elif(y_test[j] == 1 and res[j] == 0):
        FP = FP + 1
    elif(y_test[j] == 0 and res[j] == 0 ):
        TN = TN + 1
    elif(y_test[j] == 0 and res[j] == 1):
        FN = FN + 1
        
print(f"True Positive: {TP}\tFalse Positive: {FP}\tTrue Negative: {TN}\tFalse Negative: {FN}")

True Positive: 63	False Positive: 0	True Negative: 36	False Negative: 0


In [42]:
Acc = (TP+TN)/(TP+FP+TN+FN)
Acc

1.0